language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  # api_key: 6c330cc5-6eeb-49ac-9733-93786685cd5a
    secure: QQLGt30OH361MTpkKklBLRqJOarmoybauaR2hlxH1mCk2B6Oyuo40RxnFtd4sCexr2zc86q9B7hbN13uAiSrggd5tEhji+x2SZth3mEdkDGM5+6w9v1bZo79zkztJiAUcI124MU427gyk/NZLCg8mbKnqDcV7EOV4PA4TvTBGyjveJNLAWPiiXxL/npy1xDDOIKkboE9NHN8vSdMmFHt2kN+pRRDbUaU5BssRW/+6j3RcnICfuIj+1eZoi/c5R7IoEm5d+b56n37KzunsOf1hIxni3MBp9A7FG1ZPO73R/VlxTncaOqSqjJXFqxpB54LRBnSdVJOYmn2OBR3MfbLD4E5bSUg8lHvB1TZr55E7WHHoD3hre8vLCYZF+BYyHjrBi27DIf5+1P3SOl2rdaBNbQkGr8gfN5qTGMyPg7DOaiI772F06gdPQ7BwZvc/pEBX0RQSdHH4PesNnF7Jsge33WcIbuTr1RxA+kcLK9DatRc6bUpZN5nZn1/w9sci1fFTTdwBiLGqpt5aiX6vW/AvHHogzy5Ewd6o/+TEQeMHgRkbEs8aMglvpQ6WDxJ4GXwR9cMaidpelPVtvYOcacSXouSYzumYfFmMY1V6khjp1qUmsFpulEDv7ENnr/2dFTDCTGMad9Uq+lzm9s0sjFLVmBSQe1MvdDAsMOFyKjbZBA=
  app: artistogram-client
  on:
    repo: lulusanders84/artistogram-client
