language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: b58f604e-227e-4101-9d35-ce42854e085f
  app: artistogram-client
  on:
    repo: lulusanders84/artistogram
