language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 6c330cc5-6eeb-49ac-9733-93786685cd5a
  app: artistogram-client
  on:
    repo: lulusanders84/artistogram
